OUTPUT_DIR: "checkpoints/awa_16w_2s"
LOG_FILE_NAME: "AttentionNet(mid:300,hid:4096)_SGD(lr=5e-5)_NCE+1.0ReMSE(1.0,0.0)_seed=1514.log"
MODEL_FILE_NAME: "AttentionNet(mid:300,hid:4096)_SGD(lr=5e-5)_NCE+1.0ReMSE(1.0,0.0)_seed=1514.pth"
SEED: 1514
MODEL:
  META_ARCHITECTURE: "AttentionNet"
  SCALE: 20.0
  HID_DIM: 4096
  BACKBONE:
    PRETRAINED: True
    FINETUNE: True
    TYPE: 'resnet'
  ATTENTION:
    CHANNEL: 512
    WEIGHT_SHARED: True
    W2V_PATH: "/Dataset/Attribute/w2v"
  LOSS:
    LAMBDA0: 1.0
    LAMBDA1: 1.0
    LAMBDA2: 0.0
    LAMBDA3: 0.0
    REG_NORM: True
    REG_TYPE: "MSE"
  REZSL:
    USE: True
    P: 1.0
    P2: 0.0
    WEIGHT_TYPE: "in_batch"

DATASETS:
  NAME: "AWA2"
  IMAGE_SIZE: 448
  WAYS: 16
  SHOTS: 2
  SEMANTIC: 'original'

DATALOADER:
  MODE: 'episode'
  N_BATCH: 300

SOLVER:
  MAX_EPOCH: 30
  BASE_LR: 5e-5
  WEIGHT_DECAY: 1e-5
  MOMENTUM: 0.9
  GAMMA: 0.5
  STEPS: 10
  DATA_AUG: "resize_random_crop"

TEST:
  IMS_PER_BATCH: 32
  DATA_AUG: "resize_crop"
  GAMMA: 3.5
